### ISSUE TITLE
Implement fpret ABI

### ISSUE THREAD

**Issue by tgymnich** [JuliaInterop/ObjectiveC.jl#37]
We should look into implementing [`objc_msgSend_stret`](https://developer.apple.com/documentation/objectivec/1456730-objc_msgsend_stret) to support functions that return structs.

This might be the cause of issues like https://github.com/JuliaGPU/Metal.jl/issues/338.

**Comment by maleadt** [comment]
`stret` depends on the platform, so it's not for all structs. Maybe we can re-use Julia's ABI support for this, or the reimplementation in GPUCompiler.

I noticed that there's an `fpret` too.

**Comment by maleadt** [comment]
MWE from Metal.jl:

```julia
using ObjectiveC, .Foundation

load_framework("Metal")
load_framework("CoreGraphics")

struct MTLSize
    width::NSUInteger
    height::NSUInteger
    depth::NSUInteger

    MTLSize(w=1, h=1, d=1) = new(w, h, d)
end

@objcwrapper MTLDevice <: NSObject

@objcproperties MTLDevice begin
    @autoproperty maxThreadsPerThreadgroup::MTLSize
end

MTLCreateSystemDefaultDevice() =
    MTLDevice(ccall(:MTLCreateSystemDefaultDevice, id{MTLDevice}, ()))

dev = MTLCreateSystemDefaultDevice()
@show dev.maxThreadsPerThreadgroup
```

For testing it would be better to have an API in Foundation or so that needs stret, but I haven't found one yet.

**Comment by tgymnich** [comment]
Would this work https://developer.apple.com/documentation/foundation/nsstring/1410144-rangeofstring?language=objc?

**Comment by maleadt** [comment]
`NSRect` is also large, so this works:

```julia
using ObjectiveC, .Foundation

if sizeof(Ptr{Cvoid}) == 8
    const CGFloat = Float64
else
    const CGFloat = Float32
end

struct NSPoint
    x::CGFloat
    y::CGFloat
end

struct NSSize
    width::CGFloat
    height::CGFloat
end

struct NSRect
    origin::NSPoint
    size::NSSize
end

NSRect(x, y, width, height) =NSRect(NSPoint(x, y), NSSize(width, height))
NSRect() = NSRect(0, 0, 0, 0)

Foundation.NSValue(rect::NSRect) = NSValue(@objc [NSValue valueWithRect:rect::NSRect]::id{NSValue})
NSRect(val::NSValue) = @objc [val::id{NSValue} rectValue]::NSRect

rect = @show NSRect(1, 2, 3, 4)
val = NSValue(rect)
@show NSRect(val)
```

**Comment by tgymnich** [comment]
FPRet seems only relevant on 32 bit x86. https://github.com/llvm/llvm-project/blob/803e03fbb7cd97461f349fb6e235592681fc1e6c/clang/lib/Basic/Targets/X86.h#L746

**Comment by maleadt** [comment]
Great, that's a simple reproduces. Let's start with stret, I've added an initial implementation in https://github.com/JuliaInterop/ObjectiveC.jl/pull/38.

**Comment by maleadt** [comment]
> `NSDecimal` might trigger fpret on amd64 and arm64:

I guess you meant `stret`.

> FPRet seems only relevant on 32 bit x86.

Looks like we don't need to support it then.
